
1. What is the total revenue generated by male vs. female customers?

select "Gender",
       SUM("Purchase Amount (USD)") AS Revenue
from customer
Group by "Gender";
Q.total no of customers by gender?

SELECT "Gender",
COUNT(*) AS total_people
FROM customer
GROUP BY "Gender";


Q2. Which customers used a discount but still spent more than the average purchase
ount?

select "Customer ID","Discount Applied","Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes'
 and "Purchase Amount (USD)" > (SELECT AVG("Purchase Amount (USD)") 
from customer 
);

select "Discount Applied",
count(*) AS Total_Discount_Applie_count
from customer
Group by "Discount Applied";


SELECT COUNT(*) AS total_discounts_used
FROM customer
group by "Gender" = 'Female';


Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    "Item Purchased",
    ROUND(AVG("Review Rating")::numeric,2) AS "avg_rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5; 


Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select "Shipping Type",
Round(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard','Express')
Group by "Shipping Type";

--Q. to know all column headings?
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer'
ORDER BY ordinal_position;


Q5. Do subscribed customers spend more? Compare average spend and total revenue between
bscribers and non-subscribers.

SELECT "Subscription Status",
count ("Customer ID") as "Total_Customers",
Round(AVG("Purchase Amount (USD)"):: numeric,2) as Average_Spend,
Round(SUM("Purchase Amount (USD)"):: numeric,2) as Total_Revenue
from customer
GROUP BY  "Subscription Status"
ORDER BY Average_Spend,Total_Revenue DESC;

Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select "Item Purchased",
ROUND(100 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END )/COUNT(*),2) as discount_rate
from customer
group by "Item Purchased"
Order by discount_rate desc
limit 5;


Q7. Segment customers into New, Returning, and Loyal based on their total number of
evious purchases, and show the count of each segment.

with customer_type as(
select "Customer ID" ,"Previous Purchases",
CASE
WHEN "Previous Purchases" = 1  THEN 'New'
WHEN "Previous Purchases" Between  2 and 10  THEN 'Returning'
ELSE 'Loyal'
END as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment



Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select "Category",
"Item Purchased",
COUNT("Customer ID") as Total_Orders,
ROW_NUMBER() over(partition by "Category" order by  count("Customer ID") DESC) as item_rank
from customer
group by "Category","Item Purchased"
)
select item_rank ,"Category" ,"Item Purchased",Total_Orders
from  item_counts
where item_rank <=3;


Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
bscribe?

SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. What is the revenue contribution of each age group? 

SELECT 
    age_groups,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_groups
ORDER BY total_revenue DESC;


